#!/usr/bin/env python3.10
# #!/Users/myUserID/opt/anaconda3/bin/python3.9

from StartUpScript import *

import argparse
from pprint import pprint

parser = argparse.ArgumentParser()

# parser.add_argument( "echo", help = "to echo the parameter here" ) # this is for positional argument

parser.add_argument( '-if', '--infile', type = str, help = 'the file to input from' ) # for keyword argument (options)
parser.add_argument( '-iv', '--inputVar', type = str, help = 'name of the variable that is assigned a value in the input file' )

args = parser.parse_args()

if args.infile != None :                       # <------------------ note here
  print( '\n' + 'infile : ' + args.infile )

if args.inputVar != None :                     # <------------------ note here
  print( 'inputVar : ' + args.inputVar )

if args.infile != None :

  infile = open( args.infile, mode = 'r' )

  # either
  # from Result246 import *
  # or
  inputStr = infile.read()                     # <------------------ either read it (content of the entire file) in here (as ONE string)

else :

  inputStr = sys.stdin.read()                  # <------------------ or read it (content of the entire file) in here (as ONE string)

a = eval( inputStr )                           # <------------------ ！！！
a = a[0:2] + a                                 # <----- just to show that we did read in that list and were also able to make changes to it
pprint( a, width = 10, indent = 2 )            #        note that the value of a[0:2] is >>((10, 20), 30)<<
pprint( inputStr, width = 10, indent = 2 )

B( 'echo Testing of executing shell command \'ls\' : ' )
B( 'ls' )
